site_name: Quantum Learning

theme:
    name: mkdocs
    logo: assets/images/logo.jpeg

nav:
  - Home : index.md
  - Fundamentals of Quantum Computation :
    - Foundation/Ch-00.md
    - Foundation/Ch-01.md
    - Foundation/Ch-02.md

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


