site_name: Comptative-Problems

theme:
    name: mkdocs
nav:
  - Home : index.md
  - Foundation :
    - Foundation/Ch-00.md
    - Foundation/Ch-01.md
    - Foundation/Ch-02.md
  - MCQ-Problems :
     - MCQ-Problems/ML/ProblemSet-01.md
     - MCQ-Problems\readme.md

