site_name: Quantum Learning


theme:
    name: mkdocs
    logo: assets/images/logo.jpeg
    features:
        #- navigation.tabs
        - header.autohide
        - navigation.indexes
nav:
  - Home : index.md
  - Foundation :
    - Foundation/index.md

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


